export const financeStats = [
  {
    label: "TOTAL BILLED / TARGET",
    value: "₹1.42 Cr",
    subValue: "AY 2026–27",
    description: "1,248 Students enrolled",
    percentage: "100%",
    tone: "blue",
    icon: "building",
  },
  {
    label: "TOTAL REALIZED / PAID",
    value: "₹1.08 Cr",
    subValue: "76.1%",
    description: "₹3.42L reconciled this week",
    percentage: "76.1%",
    tone: "teal",
    icon: "wallet",
  },
  {
    label: "OUTSTANDING / OVERDUE",
    value: "₹34.2 Lakh",
    subValue: "23.9% Due",
    description: "184 Overdue",
    percentage: "23.9%",
    tone: "red",
    icon: "alert",
  },
  {
    label: "CONCESSIONS APPROVED",
    value: "₹8.6 Lakh",
    subValue: "42 students",
    description: "Staff wards, Sibling, Merit",
    percentage: "Approved",
    tone: "purple",
    icon: "tag",
  },
];

export const feeStudents = [
  {
    id: "ST1024",
    name: "Aarav Kumar",
    initials: "AK",
    className: "Grade 6-A",
    category: "Term 2 Recurring Tuition",
    frequency: "Quarterly Installment",
    billed: 45000,
    paid: 40000,
    balance: 5000,
    due: "04 days",
    status: "Due",
    reference: "RCPT-2026-0891",
  },
  {
    id: "ST1025",
    name: "Diya Sharma",
    initials: "DS",
    className: "Grade 6-B",
    category: "Annual Composite",
    frequency: "Tuition + Lab + SmartClass",
    billed: 92000,
    paid: 92000,
    balance: 0,
    due: "Paid",
    status: "Paid",
    reference: "RCPT-2026-0612",
  },
  {
    id: "ST1028",
    name: "Vivaan Singh",
    initials: "VS",
    className: "Grade 8-A",
    category: "Term 1 Tuition + Robotics Lab",
    frequency: "Regular Billing",
    billed: 58000,
    paid: 18000,
    balance: 40000,
    due: "28 days",
    status: "Overdue",
    reference: "INV-2026-1044",
  },
  {
    id: "ST1090",
    name: "Kabir Das",
    initials: "KD",
    className: "Grade 11-A",
    category: "Senior Secondary",
    frequency: "ISC Stream",
    billed: 62000,
    paid: 56300,
    balance: 5700,
    due: "Oct 15",
    status: "Due",
    reference: "RCPT-2026-0549",
  },
  {
    id: "ST1032",
    name: "Rhea Sen",
    initials: "RS",
    className: "Grade 6-B",
    category: "Term 1 Tuition Fee",
    frequency: "Regular Standard",
    billed: 42000,
    paid: 42000,
    balance: 0,
    due: "Paid",
    status: "Paid",
    reference: "RCPT-2026-0774",
  },
  {
    id: "ST1034",
    name: "Meera Nair",
    initials: "MN",
    className: "Grade 9-B",
    category: "Term 2 Tuition",
    frequency: "Quarterly Installment",
    billed: 51000,
    paid: 32000,
    balance: 19000,
    due: "12 days",
    status: "Due",
    reference: "INV-2026-1102",
  },
];

export const concessions = [
  {
    id: "CON-001",
    student: "Aarav Kumar",
    className: "Grade 6-A",
    type: "Sibling Concession",
    amount: "₹5,000",
    requestedBy: "School Admin",
    status: "Pending",
  },
  {
    id: "CON-002",
    student: "Kabir Das",
    className: "Grade 11-A",
    type: "Merit Scholarship",
    amount: "₹8,500",
    requestedBy: "Academic Office",
    status: "Pending",
  },
  {
    id: "CON-003",
    student: "Rhea Sen",
    className: "Grade 6-B",
    type: "Staff Ward",
    amount: "₹6,000",
    requestedBy: "HR Office",
    status: "Approved",
  },
];

export const paymentModes = [
  "UPI / Dynamic QR",
  "Physical Cash",
  "POS Card Swipe",
  "Cheque / DD",
];

export const academicYears = ["2026 – 2027", "2025 – 2026"];

export const feeTypes = [
  "Tuition & Composite",
  "Tuition Fee",
  "Transport Fee",
  "Activity Fee",
  "Lab Fee",
];

export const classes = [
  "Grade 6",
  "Grade 7",
  "Grade 8",
  "Grade 9",
  "Grade 10",
  "Grade 11",
];
