export const employees = [
  {
    id: "EMP-1014",
    name: "Dr. Rajeshwari Menon",
    email: "r.menon@brightfield.edu",
    initials: "RM",
    type: "Teaching",
    department: "Senior Faculty",
    designation: "Physics",
    roleScope: "11-A, 11-B, 12-A",
    allocation: "Physics & Lab",
    status: "Active",
    employment: "Full-time",
  },
  {
    id: "EMP-1022",
    name: "Mr. Elena Vance",
    email: "e.vance@brightfield.edu",
    initials: "EV",
    type: "Teaching",
    department: "Head of Department",
    designation: "Mathematics",
    roleScope: "9-A, 10-A, 10-B",
    allocation: "Advanced Math",
    status: "Active",
    employment: "Full-time",
  },
  {
    id: "EMP-2005",
    name: "Sunita Deshmukh",
    email: "s.deshmukh@brightfield.edu",
    initials: "SD",
    type: "Non-Teaching",
    department: "Chief Registrar",
    designation: "Admissions & Administration",
    roleScope: "Institutional Scope",
    allocation: "SIS Access",
    status: "Active",
    employment: "Full-time",
  },
  {
    id: "EMP-1035",
    name: "Vikramaditya Rao",
    email: "v.rao@brightfield.edu",
    initials: "VR",
    type: "Teaching",
    department: "Faculty",
    designation: "History & Civics",
    roleScope: "6-A, 7-A, 8-B",
    allocation: "Social Studies",
    status: "Active",
    employment: "Full-time",
  },
  {
    id: "EMP-1048",
    name: "Priya Raman",
    email: "p.raman@brightfield.edu",
    initials: "PR",
    type: "Teaching",
    department: "Grade 6 Class Teacher",
    designation: "English & Literature",
    roleScope: "6-A, 6-B, 6-C",
    allocation: "English Literature",
    status: "Active",
    employment: "Full-time",
  },
  {
    id: "EMP-3012",
    name: "Ramesh Khurana",
    email: "r.khurana@brightfield.edu",
    initials: "RK",
    type: "Support Staff",
    department: "Transport & Fleet Lead",
    designation: "Facilities & Campus Logistics",
    roleScope: "12 Bus Routes",
    allocation: "Vehicle Safety Compliance",
    status: "Active",
    employment: "Full-time",
  },
];
