export const attendanceStudents = [
  {
    id: "ST1024",
    roll: "#12",
    name: "Aarav Kumar",
    email: "aarav.k@brightfield.edu",
    initials: "AK",
    status: "Present",
    reason: "On-time homeroom",
    guardian: "Gate + Tap Synced",
    route: "Route 14",
  },
  {
    id: "ST1025",
    roll: "#14",
    name: "Diya Sharma",
    email: "diya.s@brightfield.edu",
    initials: "DS",
    status: "Absent (Excused)",
    reason: "Medical Leave: Viral fever. Doctor note uploaded by parent.",
    guardian: "SMS Ack 08:42 AM",
    route: "Self Commute",
  },
  {
    id: "ST1026",
    roll: "#18",
    name: "Rohan Mehta",
    email: "rohan.m@brightfield.edu",
    initials: "RM",
    status: "Present",
    reason: "Morning assembly leader",
    guardian: "Gate + Tap Synced",
    route: "Route 08",
  },
  {
    id: "ST1027",
    roll: "#21",
    name: "Ananya Patel",
    email: "ananya.p@brightfield.edu",
    initials: "AP",
    status: "Present",
    reason: "Standard attendance",
    guardian: "Gate + Tap Synced",
    route: "Route 14",
  },
];

export const correctionRequests = [
  {
    id: 1,
    grade: "Grade 6-B",
    student: "Rhea Sen",
    studentId: "ST1032",
    teacher: "Priya Raman",
    recorded: "Absent",
    proposed: "Present (Late)",
    time: "09:12 AM",
    reason:
      "Student arrived at 08:52 AM during Period 2 with dental clinic slip.",
  },
  {
    id: 2,
    grade: "Grade 11-A",
    student: "Kabir Das",
    studentId: "ST1090",
    teacher: "Dr. Rajeshwari Menon",
    recorded: "Present",
    proposed: "Excused Absent",
    time: "08:58 AM",
    reason:
      "Off-campus Inter-School Athletics meet participation. Duty certificate attached.",
  },
  {
    id: 3,
    grade: "Grade 8-C",
    student: "Tanisha Roy",
    studentId: "ST1048",
    teacher: "Vikramaditya Rao",
    recorded: "Absent",
    proposed: "Present",
    time: "09:02 AM",
    reason: "Late arrival marked as absent by substitute teacher.",
  },
];
