export const students = [
  {
    id: "ST1024",
    name: "Aarav Kumar",
    email: "aarav.k@brightfield.edu",
    avatar: "AK",
    className: "Grade 6",
    section: "A",
    status: "Active",
    admissionId: "ADM #ADM-2026-084",
    admissionType: "2026 · Regular",
    year: "2026-27",
  },
  {
    id: "ST1025",
    name: "Diya Sharma",
    email: "diya.s@brightfield.edu",
    avatar: "DS",
    className: "Grade 6",
    section: "B",
    status: "Active",
    admissionId: "ADM #ADM-2026-092",
    admissionType: "2026 · Regular",
    year: "2026-27",
  },
  {
    id: "ST1026",
    name: "Rohan Mehta",
    email: "rohan.m@brightfield.edu",
    avatar: "RM",
    className: "Grade 7",
    section: "A",
    status: "Active",
    admissionId: "ADM #ADM-2026-110",
    admissionType: "2026 · Transfer",
    year: "2026-27",
  },
  {
    id: "ST1027",
    name: "Ananya Patel",
    email: "ananya.p@brightfield.edu",
    avatar: "AP",
    className: "Grade 7",
    section: "B",
    status: "Active",
    admissionId: "ADM #ADM-2025-045",
    admissionType: "2025 · Regular",
    year: "2026-27",
  },
  {
    id: "ST1028",
    name: "Vivaan Singh",
    email: "vivaan.s@brightfield.edu",
    avatar: "VS",
    className: "Grade 8",
    section: "A",
    status: "Inactive",
    admissionId: "ADM #ADM-2025-018",
    admissionType: "2025 · Leave of Absence",
    year: "2026-27",
  },
  {
    id: "ST1029",
    name: "Isha Reddy",
    email: "isha.r@brightfield.edu",
    avatar: "IR",
    className: "Grade 8",
    section: "C",
    status: "Active",
    admissionId: "ADM #ADM-2026-140",
    admissionType: "2026 · Regular",
    year: "2026-27",
  },
  {
    id: "ST1030",
    name: "Rohan Mehta",
    email: "rohan.m@brightfield.edu",
    avatar: "RM",
    className: "Grade 7",
    section: "A",
    status: "Active",
    admissionId: "ADM #ADM-2026-110",
    admissionType: "2026 · Transfer",
    year: "2026-27",
  },
  {
    id: "ST1031",
    name: "Rohan Mehta",
    email: "rohan.m2@brightfield.edu",
    avatar: "RM",
    className: "Grade 7",
    section: "A",
    status: "Active",
    admissionId: "ADM #ADM-2026-110",
    admissionType: "2026 · Transfer",
    year: "2026-27",
  },
  {
    id: "ST1032",
    name: "Ananya Patel",
    email: "ananya.p2@brightfield.edu",
    avatar: "AP",
    className: "Grade 7",
    section: "B",
    status: "Active",
    admissionId: "ADM #ADM-2025-045",
    admissionType: "2025 · Regular",
    year: "2026-27",
  },
  {
    id: "ST1033",
    name: "Vivaan Singh",
    email: "vivaan.s2@brightfield.edu",
    avatar: "VS",
    className: "Grade 8",
    section: "A",
    status: "Inactive",
    admissionId: "ADM #ADM-2025-018",
    admissionType: "2025 · Leave of Absence",
    year: "2026-27",
  },
];
